language: elixir
elixir:
  - 1.9.1
otp_release:
  - 22.0.3
cache:
  directories:
    - _build
    - deps
notifications:
  email:
    on_success: never
    on_failure: always
jobs:
  include:
    - stage: check
      script:
        - mix test
    - stage: check
      script:
        - mix credo
    - stage: deploy
      if: branch = master
      script:
        - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
        - git push -f gigalixir HEAD:refs/heads/master
    - stage: verify deployment
      script: 'curl -f https://ci.gigalixirapp.com/'
