%{
  "after" => "cbc47eabe663e87be4bd8d385abd99c54b53ac00",
  "base_ref" => nil,
  "before" => "e163614343adbdb0fb1fb1f05b00498ea067d500",
  "commits" => [
    %{
      "added" => [],
      "author" => %{
        "email" => "delagrammatikas@gmail.com",
        "name" => "Marc Delagrammatikas",
        "username" => "marcdel"
      },
      "committer" => %{
        "email" => "delagrammatikas@gmail.com",
        "name" => "Marc Delagrammatikas",
        "username" => "marcdel"
      },
      "distinct" => true,
      "id" => "cbc47eabe663e87be4bd8d385abd99c54b53ac00",
      "message" => "Test",
      "modified" => ["README.md"],
      "removed" => [],
      "timestamp" => "2019-08-30T13:29:35-07:00",
      "tree_id" => "0e7b73c335ecf3621db56fbc17e254bda333da70",
      "url" =>
        "https://github.com/marcdel/ci_metrics_test/commit/cbc47eabe663e87be4bd8d385abd99c54b53ac00"
    }
  ],
  "compare" => "https://github.com/marcdel/ci_metrics_test/compare/e163614343ad...cbc47eabe663",
  "created" => false,
  "deleted" => false,
  "forced" => false,
  "head_commit" => %{
    "added" => [],
    "author" => %{
      "email" => "delagrammatikas@gmail.com",
      "name" => "Marc Delagrammatikas",
      "username" => "marcdel"
    },
    "committer" => %{
      "email" => "delagrammatikas@gmail.com",
      "name" => "Marc Delagrammatikas",
      "username" => "marcdel"
    },
    "distinct" => true,
    "id" => "cbc47eabe663e87be4bd8d385abd99c54b53ac00",
    "message" => "Test",
    "modified" => ["README.md"],
    "removed" => [],
    "timestamp" => "2019-08-30T13:29:35-07:00",
    "tree_id" => "0e7b73c335ecf3621db56fbc17e254bda333da70",
    "url" =>
      "https://github.com/marcdel/ci_metrics_test/commit/cbc47eabe663e87be4bd8d385abd99c54b53ac00"
  },
  "pusher" => %{"email" => "delagrammatikas@gmail.com", "name" => "marcdel"},
  "ref" => "refs/heads/master",
  "repository" => %{
    "statuses_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/statuses/{sha}",
    "git_refs_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/git/refs{/sha}",
    "issue_comment_url" =>
      "https://api.github.com/repos/marcdel/ci_metrics_test/issues/comments{/number}",
    "watchers" => 0,
    "disabled" => false,
    "mirror_url" => nil,
    "languages_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/languages",
    "stargazers_count" => 0,
    "license" => nil,
    "forks" => 0,
    "default_branch" => "master",
    "comments_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/comments{/number}",
    "commits_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/commits{/sha}",
    "id" => 205_447_397,
    "clone_url" => "https://github.com/marcdel/ci_metrics_test.git",
    "homepage" => nil,
    "stargazers_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/stargazers",
    "events_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/events",
    "blobs_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/git/blobs{/sha}",
    "forks_count" => 0,
    "pushed_at" => 1_567_196_988,
    "git_url" => "git://github.com/marcdel/ci_metrics_test.git",
    "hooks_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/hooks",
    "owner" => %{
      "avatar_url" => "https://avatars0.githubusercontent.com/u/693730?v=4",
      "email" => "delagrammatikas@gmail.com",
      "events_url" => "https://api.github.com/users/marcdel/events{/privacy}",
      "followers_url" => "https://api.github.com/users/marcdel/followers",
      "following_url" => "https://api.github.com/users/marcdel/following{/other_user}",
      "gists_url" => "https://api.github.com/users/marcdel/gists{/gist_id}",
      "gravatar_id" => "",
      "html_url" => "https://github.com/marcdel",
      "id" => 693_730,
      "login" => "marcdel",
      "name" => "marcdel",
      "node_id" => "MDQ6VXNlcjY5MzczMA==",
      "organizations_url" => "https://api.github.com/users/marcdel/orgs",
      "received_events_url" => "https://api.github.com/users/marcdel/received_events",
      "repos_url" => "https://api.github.com/users/marcdel/repos",
      "site_admin" => false,
      "starred_url" => "https://api.github.com/users/marcdel/starred{/owner}{/repo}",
      "subscriptions_url" => "https://api.github.com/users/marcdel/subscriptions",
      "type" => "User",
      "url" => "https://api.github.com/users/marcdel"
    },
    "trees_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/git/trees{/sha}",
    "git_commits_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/git/commits{/sha}",
    "collaborators_url" =>
      "https://api.github.com/repos/marcdel/ci_metrics_test/collaborators{/collaborator}",
    "watchers_count" => 0,
    "archived" => false,
    "tags_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/tags",
    "merges_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/merges",
    "releases_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/releases{/id}",
    "subscribers_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/subscribers",
    "ssh_url" => "git@github.com:marcdel/ci_metrics_test.git",
    "created_at" => 1_567_194_451,
    "name" => "ci_metrics_test",
    "has_issues" => true,
    "private" => true,
    "git_tags_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/git/tags{/sha}",
    "has_projects" => true,
    "archive_url" =>
      "https://api.github.com/repos/marcdel/ci_metrics_test/{archive_format}{/ref}",
    "stargazers" => 0,
    "has_wiki" => true,
    "open_issues_count" => 0,
    "milestones_url" =>
      "https://api.github.com/repos/marcdel/ci_metrics_test/milestones{/number}",
    "forks_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/forks",
    "url" => "https://github.com/marcdel/ci_metrics_test",
    "downloads_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/downloads",
    "open_issues" => 0,
    "keys_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/keys{/key_id}",
    "description" => "Repo for testing events to ci_metrics",
    "contents_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/contents/{+path}",
    "language" => nil,
    "contributors_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/contributors",
    "deployments_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/deployments",
    "pulls_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/pulls{/number}",
    "labels_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/labels{/name}",
    "master_branch" => "master",
    "html_url" => "https://github.com/marcdel/ci_metrics_test",
    "svn_url" => "https://github.com/marcdel/ci_metrics_test",
    "issue_events_url" =>
      "https://api.github.com/repos/marcdel/ci_metrics_test/issues/events{/number}",
    "notifications_url" =>
      "https://api.github.com/repos/marcdel/ci_metrics_test/notifications{?since,all,participating}",
    "has_downloads" => true,
    "node_id" => "MDEwOlJlcG9zaXRvcnkyMDU0NDczOTc=",
    "compare_url" =>
      "https://api.github.com/repos/marcdel/ci_metrics_test/compare/{base}...{head}",
    "full_name" => "marcdel/ci_metrics_test",
    "subscription_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/subscription",
    "assignees_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/assignees{/user}",
    "issues_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/issues{/number}",
    "size" => 0,
    "has_pages" => false,
    "fork" => false,
    "updated_at" => "2019-08-30T20:17:46Z",
    "branches_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/branches{/branch}",
    "teams_url" => "https://api.github.com/repos/marcdel/ci_metrics_test/teams"
  },
  "sender" => %{
    "avatar_url" => "https://avatars0.githubusercontent.com/u/693730?v=4",
    "events_url" => "https://api.github.com/users/marcdel/events{/privacy}",
    "followers_url" => "https://api.github.com/users/marcdel/followers",
    "following_url" => "https://api.github.com/users/marcdel/following{/other_user}",
    "gists_url" => "https://api.github.com/users/marcdel/gists{/gist_id}",
    "gravatar_id" => "",
    "html_url" => "https://github.com/marcdel",
    "id" => 693_730,
    "login" => "marcdel",
    "node_id" => "MDQ6VXNlcjY5MzczMA==",
    "organizations_url" => "https://api.github.com/users/marcdel/orgs",
    "received_events_url" => "https://api.github.com/users/marcdel/received_events",
    "repos_url" => "https://api.github.com/users/marcdel/repos",
    "site_admin" => false,
    "starred_url" => "https://api.github.com/users/marcdel/starred{/owner}{/repo}",
    "subscriptions_url" => "https://api.github.com/users/marcdel/subscriptions",
    "type" => "User",
    "url" => "https://api.github.com/users/marcdel"
  }
}
