name: Build and Test

on: push

jobs:
  Build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.0.3
          elixir-version: 1.9.1
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix test
      - name: Check Code Quality
        run: mix credo
      - name: Check Formatting
        run: mix format --check-formatted
