name: CI/CD

on:
  push:
    branches:
      - master
jobs:

  Test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.0.3
          elixir-version: 1.9.1
      - name: Get Deps
        run: mix deps.get
      - name: Run Tests
        run: mix test

  Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.0.3
          elixir-version: 1.9.1
      - name: Get Deps
        run: mix deps.get
      - name: Check Code Quality
        run: mix credo
      - name: Check Formatting
        run: mix format --check-formatted

  Deploy:
    runs-on: ubuntu-latest

    needs: [Test, Check]

    steps:
      - uses: actions/checkout@v1.0.0
      - name: Deploy to Prod
        env:
          GIGALIXIR_EMAIL: ${{ secrets.GIGALIXIR_EMAIL }}
          GIGALIXIR_API_KEY: ${{ secrets.GIGALIXIR_API_KEY }}
          GIGALIXIR_APP_NAME: ${{ secrets.GIGALIXIR_APP_NAME }}
        run: |
          git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
          git push -f gigalixir HEAD:refs/heads/master
      - name: Verify Deployment
        if: success()
        run: curl -f https://ci-metrics.dev/
