name: Deploy

on:
  push:
    branches:
    - master

jobs:

  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Login to Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          args: container:login
      - name: Push to Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          args: container:push -a amadeus-cho web --arg SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }},DATABASE_URL=${{ secrets.DATABASE_URL }}
      - name: Create Heroku Release
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          args: container:release -a amadeus-cho web
